# Generated by Django 3.2.3 on 2021-05-24 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='headline',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
