# Generated by Django 3.2.3 on 2021-05-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20210524_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='stories',
        ),
        migrations.AddField(
            model_name='story',
            name='content',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
