# Generated by Django 3.2.3 on 2021-05-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20210524_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrazySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('last_date', models.DateField()),
                ('banner', models.ImageField(upload_to='images/')),
                ('headline', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('placeholder', models.TextField()),
            ],
        ),
    ]
