# Generated by Django 3.2.3 on 2021-05-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_crazysales_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('banner', models.ImageField(upload_to='images/')),
                ('headline', models.CharField(max_length=200)),
                ('conter', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='CrazySales',
            new_name='CrazySale',
        ),
    ]
