# Generated by Django 3.2.3 on 2021-07-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20210525_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likedapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
